repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
        entry: python -m pre_commit_hooks.check_case_conflict
      - id: check-json
        exclude: ^frontend/tsconfig\.json$
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
        entry: python -m pre_commit_hooks.mixed_line_ending
        args: ["--fix=lf"]

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npm run lint
        language: system
        pass_filenames: false
        files: ^(frontend/.*|functions/.*|tests/.*|package(-lock)?\.json)$

      - id: typecheck
        name: typecheck
        entry: npm run typecheck
        language: system
        pass_filenames: false
        files: ^(frontend|backend)/(src|package(-lock)?\.json|tsconfig\.json)
        types_or: [ts, tsx, json]

      - id: frontend-lit-analyzer
        name: frontend lit analyzer
        entry: npm run frontend:analyze
        language: system
        pass_filenames: false
        files: ^frontend/(src|package(-lock)?\.json|tsconfig\.json)
        types_or: [ts, tsx, json]

      - id: terraform_fmt
        name: Terraform fmt
        entry: terraform -chdir=terraform fmt -check -recursive
        language: system
        pass_filenames: false
        files: ^terraform/.*\.tf$

      - id: terraform_validate
        name: Terraform validate
        entry: sh -c 'terraform -chdir=terraform init -backend=false -input=false && terraform -chdir=terraform validate'
        language: system
        pass_filenames: false
        files: ^terraform/.*\.tf$

      - id: terraform_docs
        name: Terraform docs
        entry: terraform-docs --config terraform/.terraform-docs.yml terraform
        language: system
        pass_filenames: false
        files: ^terraform/.*\.tf$
